services:
  cado-engine:
    build:
      context: ./cado-src
      dockerfile: Dockerfile
    image: primeval/cado-engine:latest
    container_name: cado-engine
    tty: true
    stdin_open: true
    volumes:
      - ./data:/work
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["tail", "-f", "/dev/null"]
